services:
  entrenador_ia:
    build:
      context: ./herramientas_ia_radiografia
      dockerfile: Dockerfile

    profiles:
      - ml

    working_dir: /workspace

    environment:
      PYTHONUNBUFFERED: "1"
      HF_HOME: /workspace/.cache/huggingface
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

    gpus: all

    volumes:
      - ./herramientas_ia_radiografia:/workspace
      - ./datos_radiografias_san_juan_de_dios:/datos_radiografias_san_juan_de_dios
      - ./servicios/servicio_ia/modelos:/modelos
