# Generated by Django 5.2.17 on 2026-08-23 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquitecturaModelo',
            fields=[
                ('id_arquitectura', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arquitecturas_modelo',
            },
        ),
        migrations.CreateModel(
            name='ClaseDataset',
            fields=[
                ('id_clase', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'clases_dataset',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id_dataset', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='EstadoExperimento',
            fields=[
                ('id_estado_experimento', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_experimento',
            },
        ),
        migrations.CreateModel(
            name='EstadoInferencia',
            fields=[
                ('id_estado_inferencia', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_inferencia',
            },
        ),
        migrations.CreateModel(
            name='EstadoModelo',
            fields=[
                ('id_estado_modelo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_modelo',
            },
        ),
        migrations.CreateModel(
            name='EstadoVersionDataset',
            fields=[
                ('id_estado_version', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_version_dataset',
            },
        ),
        migrations.CreateModel(
            name='Optimizador',
            fields=[
                ('id_optimizador', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'optimizadores',
            },
        ),
        migrations.CreateModel(
            name='ParticionDataset',
            fields=[
                ('id_particion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'particiones_dataset',
            },
        ),
        migrations.CreateModel(
            name='TipoArtefacto',
            fields=[
                ('id_tipo_artefacto', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipos_artefacto',
            },
        ),
        migrations.CreateModel(
            name='TipoMetrica',
            fields=[
                ('id_tipo_metrica', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipos_metrica',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPreprocesamiento',
            fields=[
                ('id_config_preproc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ancho_objetivo', models.PositiveIntegerField()),
                ('alto_objetivo', models.PositiveIntegerField()),
                ('normalizacion', models.CharField(blank=True, max_length=120, null=True)),
                ('aumento_datos', models.BooleanField(default=False)),
                ('configuracion_aumento', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'config_preprocesamiento',
                'constraints': [models.CheckConstraint(condition=models.Q(('ancho_objetivo__gt', 0)), name='ck_preproc_ancho'), models.CheckConstraint(condition=models.Q(('alto_objetivo__gt', 0)), name='ck_preproc_alto')],
            },
        ),
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id_experimento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_por_uuid', models.UUIDField(blank=True, null=True)),
                ('config_preprocesamiento', models.ForeignKey(db_column='id_config_preproc', on_delete=django.db.models.deletion.PROTECT, related_name='experimentos', to='inteligencia.configuracionpreprocesamiento')),
                ('estado_experimento', models.ForeignKey(db_column='id_estado_experimento', on_delete=django.db.models.deletion.PROTECT, related_name='experimentos', to='inteligencia.estadoexperimento')),
            ],
            options={
                'db_table': 'experimentos',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('version', models.PositiveIntegerField()),
                ('ruta_modelo', models.CharField(max_length=500)),
                ('hash_modelo', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_modelo', models.ForeignKey(db_column='id_estado_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inteligencia.estadomodelo')),
                ('experimento', models.ForeignKey(db_column='id_experimento', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inteligencia.experimento')),
            ],
            options={
                'db_table': 'modelos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEntrenamiento',
            fields=[
                ('id_config_entrenamiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learning_rate', models.DecimalField(decimal_places=10, max_digits=12)),
                ('batch_size', models.PositiveIntegerField()),
                ('epochs', models.PositiveIntegerField()),
                ('fine_tuning', models.BooleanField(default=False)),
                ('capas_descongeladas', models.PositiveIntegerField(blank=True, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('parametros_adicionales', models.JSONField(blank=True, null=True)),
                ('arquitectura', models.ForeignKey(db_column='id_arquitectura', on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones', to='inteligencia.arquitecturamodelo')),
                ('experimento', models.OneToOneField(db_column='id_experimento', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_entrenamiento', to='inteligencia.experimento')),
                ('optimizador', models.ForeignKey(db_column='id_optimizador', on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones', to='inteligencia.optimizador')),
            ],
            options={
                'db_table': 'config_entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='SolicitudInferencia',
            fields=[
                ('id_solicitud_inferencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radiografia_uuid', models.UUIDField()),
                ('caso_uuid', models.UUIDField()),
                ('solicitado_por_uuid', models.UUIDField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('numero_intentos', models.PositiveSmallIntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('estado_inferencia', models.ForeignKey(db_column='id_estado_inferencia', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inteligencia.estadoinferencia')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_inferencia', to='inteligencia.modelo')),
            ],
            options={
                'db_table': 'solicitudes_inferencia',
            },
        ),
        migrations.CreateModel(
            name='ResultadoInferencia',
            fields=[
                ('id_resultado_inferencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probabilidad', models.DecimalField(decimal_places=7, max_digits=8)),
                ('tiempo_procesamiento_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
                ('clase_predicha', models.ForeignKey(db_column='id_clase_predicha', on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='inteligencia.clasedataset')),
                ('solicitud', models.OneToOneField(db_column='id_solicitud_inferencia', on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='inteligencia.solicitudinferencia')),
            ],
            options={
                'db_table': 'resultados_inferencia',
            },
        ),
        migrations.CreateModel(
            name='ArtefactoExplicabilidad',
            fields=[
                ('id_artefacto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(db_column='id_resultado_inferencia', on_delete=django.db.models.deletion.CASCADE, related_name='artefactos', to='inteligencia.resultadoinferencia')),
                ('tipo_artefacto', models.ForeignKey(db_column='id_tipo_artefacto', on_delete=django.db.models.deletion.PROTECT, related_name='artefactos', to='inteligencia.tipoartefacto')),
            ],
            options={
                'db_table': 'artefactos_explicabilidad',
            },
        ),
        migrations.CreateModel(
            name='MetricaExperimento',
            fields=[
                ('id_metrica_experimento', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=8, max_digits=12)),
                ('epoch', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('experimento', models.ForeignKey(db_column='id_experimento', on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='inteligencia.experimento')),
                ('particion', models.ForeignKey(db_column='id_particion', on_delete=django.db.models.deletion.PROTECT, related_name='metricas', to='inteligencia.particiondataset')),
                ('tipo_metrica', models.ForeignKey(db_column='id_tipo_metrica', on_delete=django.db.models.deletion.PROTECT, related_name='metricas', to='inteligencia.tipometrica')),
            ],
            options={
                'db_table': 'metricas_experimento',
            },
        ),
        migrations.CreateModel(
            name='UmbralModelo',
            fields=[
                ('id_umbral', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_umbral', models.DecimalField(decimal_places=5, max_digits=6)),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.PROTECT, related_name='umbrales', to='inteligencia.clasedataset')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, related_name='umbrales', to='inteligencia.modelo')),
            ],
            options={
                'db_table': 'umbrales_modelo',
            },
        ),
        migrations.CreateModel(
            name='VersionDataset',
            fields=[
                ('id_version_dataset', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.PositiveIntegerField()),
                ('cantidad_imagenes', models.PositiveIntegerField(default=0)),
                ('hash_manifiesto', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(db_column='id_dataset', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='inteligencia.dataset')),
                ('estado_version', models.ForeignKey(db_column='id_estado_version', on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='inteligencia.estadoversiondataset')),
            ],
            options={
                'db_table': 'versiones_dataset',
            },
        ),
        migrations.CreateModel(
            name='ImagenDataset',
            fields=[
                ('id_imagen_dataset', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_imagen', models.CharField(max_length=500)),
                ('hash_imagen', models.CharField(blank=True, max_length=64, null=True)),
                ('paciente_anonimo_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.PROTECT, related_name='imagenes', to='inteligencia.clasedataset')),
                ('particion', models.ForeignKey(db_column='id_particion', on_delete=django.db.models.deletion.PROTECT, related_name='imagenes', to='inteligencia.particiondataset')),
                ('version_dataset', models.ForeignKey(db_column='id_version_dataset', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inteligencia.versiondataset')),
            ],
            options={
                'db_table': 'imagenes_dataset',
            },
        ),
        migrations.AddField(
            model_name='experimento',
            name='version_dataset',
            field=models.ForeignKey(db_column='id_version_dataset', on_delete=django.db.models.deletion.PROTECT, related_name='experimentos', to='inteligencia.versiondataset'),
        ),
        migrations.AddIndex(
            model_name='modelo',
            index=models.Index(fields=['estado_modelo'], name='idx_modelo_estado'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('nombre', 'version'), name='uq_modelo_version'),
        ),
        migrations.AddConstraint(
            model_name='configuracionentrenamiento',
            constraint=models.CheckConstraint(condition=models.Q(('learning_rate__gt', 0)), name='ck_train_lr'),
        ),
        migrations.AddConstraint(
            model_name='configuracionentrenamiento',
            constraint=models.CheckConstraint(condition=models.Q(('batch_size__gt', 0)), name='ck_train_batch'),
        ),
        migrations.AddConstraint(
            model_name='configuracionentrenamiento',
            constraint=models.CheckConstraint(condition=models.Q(('epochs__gt', 0)), name='ck_train_epochs'),
        ),
        migrations.AddIndex(
            model_name='solicitudinferencia',
            index=models.Index(fields=['estado_inferencia', 'fecha_solicitud'], name='idx_inf_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitudinferencia',
            index=models.Index(fields=['radiografia_uuid'], name='idx_inf_radiografia'),
        ),
        migrations.AddIndex(
            model_name='solicitudinferencia',
            index=models.Index(fields=['caso_uuid'], name='idx_inf_caso'),
        ),
        migrations.AddConstraint(
            model_name='resultadoinferencia',
            constraint=models.CheckConstraint(condition=models.Q(('probabilidad__gte', 0), ('probabilidad__lte', 1)), name='ck_resultado_prob'),
        ),
        migrations.AddConstraint(
            model_name='artefactoexplicabilidad',
            constraint=models.UniqueConstraint(fields=('resultado', 'tipo_artefacto'), name='uq_resultado_artefacto'),
        ),
        migrations.AddIndex(
            model_name='metricaexperimento',
            index=models.Index(fields=['experimento', 'tipo_metrica'], name='idx_metrica_exp_tipo'),
        ),
        migrations.AddConstraint(
            model_name='umbralmodelo',
            constraint=models.UniqueConstraint(fields=('modelo', 'clase'), name='uq_umbral_modelo_clase'),
        ),
        migrations.AddConstraint(
            model_name='umbralmodelo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_umbral__gte', 0), ('valor_umbral__lte', 1)), name='ck_umbral_rango'),
        ),
        migrations.AddIndex(
            model_name='versiondataset',
            index=models.Index(fields=['dataset', 'estado_version'], name='idx_dataset_estado'),
        ),
        migrations.AddConstraint(
            model_name='versiondataset',
            constraint=models.UniqueConstraint(fields=('dataset', 'numero_version'), name='uq_dataset_version'),
        ),
        migrations.AddIndex(
            model_name='imagendataset',
            index=models.Index(fields=['version_dataset', 'particion'], name='idx_img_version_part'),
        ),
        migrations.AddIndex(
            model_name='imagendataset',
            index=models.Index(fields=['clase', 'particion'], name='idx_img_clase_part'),
        ),
        migrations.AddConstraint(
            model_name='imagendataset',
            constraint=models.UniqueConstraint(fields=('version_dataset', 'referencia_imagen'), name='uq_version_imagen'),
        ),
        migrations.AddIndex(
            model_name='experimento',
            index=models.Index(fields=['version_dataset', 'estado_experimento'], name='idx_exp_dataset_estado'),
        ),
    ]
