import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inteligencia",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisRadiografiaIA",
            fields=[
                (
                    "id_analisis",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "radiografia_uuid",
                    models.UUIDField(),
                ),
                (
                    "caso_uuid",
                    models.UUIDField(),
                ),
                (
                    "solicitado_por_uuid",
                    models.UUIDField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "es_radiografia",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "anatomia_evaluada",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "anatomia_admitida",
                    models.BooleanField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "analisis_osteosarcoma_evaluado",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "osteosarcoma_sospechoso",
                    models.BooleanField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "probabilidad_osteosarcoma",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "probabilidad_no_osteosarcoma",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "localizacion_evaluada",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "localizacion_detectada",
                    models.BooleanField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "confianza_localizacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "umbral_localizacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "x1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "y1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "x2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "y2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "etapa_rechazo",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "resultado_json",
                    models.JSONField(),
                ),
                (
                    "fecha_analisis",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                "db_table":
                    "analisis_radiografia_ia",
            },
        ),
        migrations.AddIndex(
            model_name="analisisradiografiaia",
            index=models.Index(
                fields=[
                    "radiografia_uuid",
                    "fecha_analisis",
                ],
                name="idx_ia_rad_fecha",
            ),
        ),
        migrations.AddIndex(
            model_name="analisisradiografiaia",
            index=models.Index(
                fields=[
                    "caso_uuid",
                    "fecha_analisis",
                ],
                name="idx_ia_caso_fecha",
            ),
        ),
    ]
