# Generated by Django 5.2.17 on 2026-08-23 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSigno',
            fields=[
                ('id_signo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'catalogo_signos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoSintoma',
            fields=[
                ('id_sintoma', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'catalogo_sintomas',
            },
        ),
        migrations.CreateModel(
            name='CriterioValoracion',
            fields=[
                ('id_criterio', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'criterios_valoracion',
            },
        ),
        migrations.CreateModel(
            name='EstadoCaso',
            fields=[
                ('id_estado_caso', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_caso',
            },
        ),
        migrations.CreateModel(
            name='NivelIntensidad',
            fields=[
                ('id_nivel_intensidad', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'niveles_intensidad',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='PrioridadCaso',
            fields=[
                ('id_prioridad', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'prioridades_caso',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sexos',
            },
        ),
        migrations.CreateModel(
            name='TipoAntecedente',
            fields=[
                ('id_tipo_antecedente', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipos_antecedente',
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id_tipo_contacto', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipos_contacto',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id_caso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_caso', models.CharField(max_length=50, unique=True)),
                ('oncologo_responsable_uuid', models.UUIDField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_consulta', models.TextField()),
                ('observacion_general', models.TextField(blank=True, null=True)),
                ('estado_caso', models.ForeignKey(db_column='id_estado_caso', on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clinica.estadocaso')),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='casos_clinicos', to='clinica.paciente')),
                ('prioridad', models.ForeignKey(db_column='id_prioridad', on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clinica.prioridadcaso')),
            ],
            options={
                'db_table': 'casos_clinicos',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinica.sexo'),
        ),
        migrations.CreateModel(
            name='AntecedenteClinico',
            fields=[
                ('id_antecedente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='clinica.paciente')),
                ('tipo_antecedente', models.ForeignKey(db_column='id_tipo_antecedente', on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes', to='clinica.tipoantecedente')),
            ],
            options={
                'db_table': 'antecedentes_clinicos',
            },
        ),
        migrations.CreateModel(
            name='ContactoPaciente',
            fields=[
                ('id_contacto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=150)),
                ('principal', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clinica.paciente')),
                ('tipo_contacto', models.ForeignKey(db_column='id_tipo_contacto', on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='clinica.tipocontacto')),
            ],
            options={
                'db_table': 'contactos_paciente',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('expedido_en', models.CharField(blank=True, max_length=40, null=True)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clinica.paciente')),
                ('tipo_documento', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='clinica.tipodocumento')),
            ],
            options={
                'db_table': 'documentos_paciente',
            },
        ),
        migrations.CreateModel(
            name='ValoracionEspecialista',
            fields=[
                ('id_valoracion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oncologo_uuid', models.UUIDField()),
                ('resultado_ia_uuid', models.UUIDField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='clinica.casoclinico')),
                ('criterio', models.ForeignKey(db_column='id_criterio', on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones', to='clinica.criteriovaloracion')),
            ],
            options={
                'db_table': 'valoraciones_especialista',
            },
        ),
        migrations.CreateModel(
            name='CasoSigno',
            fields=[
                ('id_caso_signo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_hallazgo', models.TextField(blank=True, null=True)),
                ('fecha_observacion', models.DateTimeField(auto_now_add=True)),
                ('observado_por_uuid', models.UUIDField()),
                ('caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.CASCADE, related_name='signos', to='clinica.casoclinico')),
                ('signo', models.ForeignKey(db_column='id_signo', on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clinica.catalogosigno')),
            ],
            options={
                'db_table': 'caso_signo',
                'constraints': [models.UniqueConstraint(fields=('caso', 'signo'), name='uq_caso_signo')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoCaso',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_uuid', models.UUIDField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='clinica.casoclinico')),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_anterior', to='clinica.estadocaso')),
                ('estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_nuevo', to='clinica.estadocaso')),
            ],
            options={
                'db_table': 'historial_estado_caso',
                'indexes': [models.Index(fields=['caso', 'fecha_cambio'], name='idx_hist_caso_fecha')],
            },
        ),
        migrations.CreateModel(
            name='CasoSintoma',
            fields=[
                ('id_caso_sintoma', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='clinica.casoclinico')),
                ('sintoma', models.ForeignKey(db_column='id_sintoma', on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clinica.catalogosintoma')),
                ('intensidad', models.ForeignKey(blank=True, db_column='id_nivel_intensidad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sintomas_caso', to='clinica.nivelintensidad')),
            ],
            options={
                'db_table': 'caso_sintoma',
                'constraints': [models.UniqueConstraint(fields=('caso', 'sintoma'), name='uq_caso_sintoma')],
            },
        ),
        migrations.AddIndex(
            model_name='casoclinico',
            index=models.Index(fields=['paciente', 'fecha_apertura'], name='idx_caso_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='casoclinico',
            index=models.Index(fields=['estado_caso', 'prioridad'], name='idx_caso_estado_prior'),
        ),
        migrations.AddIndex(
            model_name='casoclinico',
            index=models.Index(fields=['oncologo_responsable_uuid'], name='idx_caso_oncologo'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido_paterno', 'nombres'], name='idx_paciente_nombre'),
        ),
        migrations.AddIndex(
            model_name='antecedenteclinico',
            index=models.Index(fields=['paciente', 'tipo_antecedente'], name='idx_ant_paciente_tipo'),
        ),
        migrations.AddIndex(
            model_name='contactopaciente',
            index=models.Index(fields=['paciente', 'principal'], name='idx_contacto_principal'),
        ),
        migrations.AddConstraint(
            model_name='documentopaciente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='uq_doc_tipo_numero'),
        ),
        migrations.AddIndex(
            model_name='valoracionespecialista',
            index=models.Index(fields=['caso', 'fecha_valoracion'], name='idx_val_caso_fecha'),
        ),
    ]
