# Generated by Django 5.2.17 on 2026-09-09 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_seed_catalogos_clinicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmergenciaPaciente',
            fields=[
                ('id_contacto_emergencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=180)),
                ('parentesco', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=25)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('principal', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='clinica.paciente')),
            ],
            options={
                'db_table': 'contactos_emergencia_paciente',
                'indexes': [models.Index(fields=['paciente', 'principal'], name='idx_contacto_emergencia')],
            },
        ),
    ]
