# Generated by Django 5.2.17 on 2026-09-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_actualizar_estados_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='pacientes/fotos/%Y/%m/'),
        ),
    ]
