# Generated by Django 5.2.17 on 2026-09-11 23:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_paciente_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoObservacion',
            fields=[
                ('id_observacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('registrado_por_uuid', models.UUIDField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'caso_observaciones',
            },
        ),
        migrations.AddField(
            model_name='antecedenteclinico',
            name='registrado_por_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casosintoma',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='casosintoma',
            name='registrado_por_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='casosigno',
            index=models.Index(fields=['caso', 'fecha_observacion'], name='idx_signo_caso_fecha'),
        ),
        migrations.AddIndex(
            model_name='casosintoma',
            index=models.Index(fields=['caso', 'fecha_registro'], name='idx_sintoma_caso_fecha'),
        ),
        migrations.AddField(
            model_name='casoobservacion',
            name='caso',
            field=models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_clinicas', to='clinica.casoclinico'),
        ),
        migrations.AddIndex(
            model_name='casoobservacion',
            index=models.Index(fields=['caso', 'fecha_registro'], name='idx_obs_caso_fecha'),
        ),
    ]
