# Generated by Django 5.2.17 on 2026-08-26 01:22

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRecuperacion',
            fields=[
                ('id_estado_recuperacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_usuario', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_operativo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estados_usuario',
                'ordering': ['id_estado_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('modulo', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permisos',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id_rol'],
            },
        ),
        migrations.CreateModel(
            name='TipoEventoAcceso',
            fields=[
                ('id_tipo_evento', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipos_evento_acceso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80, null=True)),
                ('correo', models.CharField(max_length=150)),
                ('nombre_usuario', models.CharField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('estado_usuario', models.ForeignKey(db_column='id_estado_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='identidad.estadousuario')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudRecuperacion',
            fields=[
                ('id_solicitud', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('token_recuperacion', models.CharField(max_length=255, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_recuperacion', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='identidad.estadorecuperacion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recuperacion', to='identidad.usuario')),
            ],
            options={
                'db_table': 'solicitudes_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti_refresh', models.UUIDField(unique=True)),
                ('refresh_token_hash', models.CharField(max_length=255)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('revocada', models.BooleanField(default=False)),
                ('motivo_revocacion', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='identidad.usuario')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
        migrations.CreateModel(
            name='ResolucionRecuperacion',
            fields=[
                ('id_resolucion', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='identidad.solicitudrecuperacion')),
                ('revisado_por', models.ForeignKey(db_column='id_usuario_revisor', on_delete=django.db.models.deletion.PROTECT, related_name='recuperaciones_revisadas', to='identidad.usuario')),
            ],
            options={
                'db_table': 'resoluciones_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id_perfil_profesional', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula_profesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=120, null=True)),
                ('subespecialidad', models.CharField(blank=True, max_length=120, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_institucional', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='identidad.usuario')),
            ],
            options={
                'db_table': 'perfiles_profesionales',
            },
        ),
        migrations.CreateModel(
            name='EventoAcceso',
            fields=[
                ('id_evento', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('tipo_evento', models.ForeignKey(db_column='id_tipo_evento', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='identidad.tipoeventoacceso')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_acceso', to='identidad.usuario')),
            ],
            options={
                'db_table': 'eventos_acceso',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id_credencial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('debe_cambiar_password', models.BooleanField(default=False)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_cambio', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='identidad.usuario')),
            ],
            options={
                'db_table': 'credenciales',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignado_por', models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados_por_mi', to='identidad.usuario')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuarios', to='identidad.rol')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to='identidad.usuario')),
            ],
            options={
                'db_table': 'usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='identidad.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='identidad.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso')],
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), name='uq_usuarios_correo_lower'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre_usuario'), name='uq_usuarios_nombre_usuario_lower'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('correo', ''), _negated=True), name='ck_usuarios_correo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_usuario', ''), _negated=True), name='ck_usuarios_nombre_usuario_no_vacio'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['usuario'], name='idx_sesion_usuario'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['revocada', 'fecha_expiracion'], name='idx_sesion_estado'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol'),
        ),
    ]
