# Generated by Django 5.2.17 on 2026-09-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidad', '0004_remove_legacy_access_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofesional',
            name='area_clinica',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci_complemento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci_expedido',
            field=models.CharField(blank=True, choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BE', 'Beni'), ('PD', 'Pando')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(('ci_numero__isnull', False)), fields=('ci_numero', 'ci_complemento'), name='uq_usuarios_ci_complemento', nulls_distinct=False),
        ),
    ]
